### ISSUE TITLE
Filtre défaillant

### ISSUE THREAD

**Issue by mohandhmd** [squelix/svelte-portfolio#12]
Bonjour,

Petit bug trouvé au niveau des filtres, impossible d'en retirer. A la mise à jour de ces derniers la sélection complète s'ajoute au filtre à nouveau plutôt que de mettre à jour le dernier item ou d'écraser la sélection précédente.

[Petite vidéo du bug](https://user-images.githubusercontent.com/76428677/213687658-5ad47a6d-fddb-46fd-a87a-fae99e3bdae8.webm), autrement site très sympa.

Bonne journée

**Comment by squelix** [comment]
Ok je vais corriger ça, merci pour le retour :)
